import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#F0F0F0',
    },
    header: {
      width: '100%',
      padding: 10,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#DDD',
      borderBottomWidth: 1,
      borderBottomColor: '#DDD',
    },
    headerText: {
      fontSize: 18,
      color: '#3498DB',
      fontWeight: 'bold',
    },
    currencyPurchaseContainer: {
      flex: 0.45,
      backgroundColor: '#468faf',
      alignItems: 'center',
      justifyContent: 'center',
      borderBottomStartRadius: 24,
      borderBottomEndRadius: 24,
    },
    currencyContainer: {
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 15,
      paddingVertical: 25,
      marginBottom: 20,
      marginTop: 20,
      borderRadius: 10,
    },
    currencyInputPicker: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      width: '80%',
      borderWidth: 1,
      borderColor: '#3498DB',
      borderRadius: 20,
      paddingHorizontal: 10,
      backgroundColor: '#FFF',
      marginHorizontal: 10,
    },
    currencyInput: {
      flex: 1,
      height: 50,
    },
    currencyPicker: {
      flex: 1,
      height: 50,
      overflow: 'hidden',
    },
    reverseButton: {
      justifyContent: 'center',
      alignItems: 'center',
      width: '17%',
      paddingVertical: 5,
      paddingHorizontal: 20,
      borderRadius: 70,
      backgroundColor: '#FFF',
      marginHorizontal: 10,
      marginVertical: 10,
      elevation: 2,
    },
    accounstAndBuyButton: {
      flex: 0.55,
      alignItems: 'center',
      justifyContent: 'center',
    },
    titleWallets: {
      alignContent: 'flex-start',
      justifyContent: 'flex-start',
    },
    accountButton: {
      padding: 10,
      margin: 5,
      backgroundColor: '#D3D3D3',
      borderRadius: 5,
      height: 100,
    },
    selectedAccount: {
      backgroundColor: '#468faf',
    },
    accountContainer: {
      flexDirection: 'row',
      marginTop: 20,
      marginBottom: 20,
    },
    purchaseButton: {
      width: '90%',
      height: 50,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#3498DB',
      borderRadius: 25,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 4,
      elevation: 3,
    },
    disabledButton: {
      backgroundColor: '#B0B0B0',
    },
    purchaseButtonText: {
      color: '#FFF',
      fontSize: 18,
      fontWeight: 'bold',
    },
    walletInfoContainer: {
      flexDirection: 'row',
      justifyContent: 'space-around',
      alignItems: 'center',
      padding: 7,
      margin: 5,
      height: 140,
      width: '100%',
    },
    walletInfoBlock: {
      alignItems: 'center',
      backgroundColor: '#D3D3D3',
      borderRadius: 5,
      height: 120,
    },
    walletInfoText: {
      flex: 1,
      marginRight: 10,
    },
  
    cancelSelectionButton: {
      position: 'absolute',
      top: 1,
      right: 0,
      padding: 5,
    },
  
    modalContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
    },
    modalContent: {
      backgroundColor: '#FFF',
      borderRadius: 10,
      padding: 20,
      width: '80%',
    },
    modalTitle: {
      fontSize: 18,
      fontWeight: 'bold',
      marginBottom: 10,
    },
    modalText: {
      fontSize: 16,
      marginBottom: 20,
    },
    modalButtonsContainer: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
    },
    modalButton: {
      marginLeft: 10,
    },
    modalButtonText: {
      fontSize: 16,
      color: '#034F84',
    },
    messageContainer: {
      position: 'absolute',
      top: 20,
      alignSelf: 'center',
      backgroundColor: 'rgba(0, 0, 0, 0.7)',
      paddingVertical: 10,
      paddingHorizontal: 20,
      borderRadius: 10,
    },
    successMessage: {
      color: '#34C759',
      fontSize: 16,
      fontWeight: 'bold',
    },
    errorMessage: {
      color: '#FF3B30',
      fontSize: 16,
      fontWeight: 'bold',
    },
  });